name: Build tun2proxy for OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          SDKDIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*")
          mv "$SDKDIR" sdk

      - name: Copy tun2proxy into SDK
        run: |
          mkdir -p sdk/package/tun2proxy
          cp -r ./* sdk/package/tun2proxy

      - name: Build tun2proxy
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/tun2proxy/compile V=s

      - name: Upload compiled IPK
        uses: actions/upload-artifact@v3
        with:
          name: tun2proxy_ipk
          path: |
            sdk/bin/packages/*/*/tun2proxy_*.ipk
